version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      - net-wordpress
    volumes:
       - 'vol-mysql:/var/lib/mysql'
    ports:
      - '3306:3306'

  wordpress:
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - net-wordpress
    volumes:
      - './html:/var/www/html'
    depends_on:
      - mysql
    ports:
      - '80:80'
    
volumes:
  vol-mysql:

networks:
  net-wordpress:
