version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    env_file: './.env'
    networks:
      - net-guacamole
    volumes:
      - './conf/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql'
      - 'vol-mysql:/var/lib/mysql'
  
  guacamole-daemon:
    image: guacamole/guacd
    container_name: guacamole-daemon
    hostname: guacamole-daemon
    depends_on:
      - mysql
    networks:
      - net-guacamole
    
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    hostname: guacamole
    depends_on:
      - guacamole-daemon
    env_file: './.env'
    networks:
      - net-guacamole
    
  guacamole-proxy:
    container_name: guacamole-proxy
    hostname: guacamole-proxy
    image: nginx
    depends_on:
      - guacamole
    networks:
      - net-guacamole
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'

volumes:
  vol-mysql:

networks:
  net-guacamole:

