version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: docker-db
      MYSQL_USER: docker-user
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'