version: '3'
services:
  apache-1:
    image: httpd:latest
    container_name: apache-1
    ports:
      - '80:80'
    networks:
      - net-test

  apache-2:
    image: httpd:latest
    container_name: apache-2
    ports:
      - '81:80'
    networks:
      - net-test
    
networks:
  net-test: