version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    volumes:
       - 'vol-mysql:/var/lib/mysql'
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: prestashop
       MYSQL_USER: prestashop
       MYSQL_PASSWORD: 123456
    networks:
      - net-prestashop
    ports:
      - '3306:3306'

  prestashop:
    image: prestashop/prestashop
    container_name: prestashop
    hostname: prestashop
    depends_on:
      - mysql
    environment:
      DB_SERVER: mysql
      DB_USER: prestashop
      DB_PASSWD: 123456
      DB_NAME: prestashop
    networks:
      - net-prestashop
    volumes:
      - 'vol-prestashop:/var/www/html'
    ports:
      - '80:80'

volumes: 
  vol-mysql:
  vol-prestashop:

networks:
  net-prestashop:
